# Arm connection Settings

serial_port:
  # Should be overridden in the launch file
  name: "" # "/dev/ttyUSB0"
  baudrate: 1000000

arm_config:
  count: 6
  devices:
    - id: 1
      model: "H54-200-S500-R"
      protocol: 2.0
      joint_name: "shoulder_pan_joint"
    - id: 2
      model: "H54-200-S500-R"
      protocol: 2.0
      joint_name: "shoulder_lift_joint"
    - id: 3
      model: "H54-100-S500-R"
      protocol: 2.0
      joint_name: "elbow_joint"
    - id: 4
      model: "H54-100-S500-R"
      protocol: 2.0
      joint_name: "wrist_1_joint"
    - id: 5
      model: "H42-20-S300-R"
      protocol: 2.0
      joint_name: "wrist_2_joint"
    - id: 6
      model: "H42-20-S300-R"
      protocol: 2.0
      joint_name: "wrist_3_joint"

# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
