# Joint names for the gazebo control plugin
joint_names:
   - shoulder_pan_joint
   - shoulder_lift_joint
   - elbow_joint
   - wrist_1_joint
   - wrist_2_joint
   - wrist_3_joint

gazebo_ros_control/pid_gains:
  shoulder_pan_joint:
    p: 9000
    i: 0.01
    d: 500
  shoulder_lift_joint:
    p: 9000
    i: 0.01
    d: 500
  elbow_joint:
    p: 9000
    i: 0.01
    d: 500
  wrist_1_joint:
    p: 6000
    i: 0.01
    d: 400
  wrist_2_joint:
    p: 6000
    i: 0.01
    d: 400
  wrist_3_joint:
    p: 6000
    i: 0.01
    d: 400
